language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - REQUESTS_VERSION=2.3.0
  - REQUESTS_VERSION=2.4.3


# command to install dependencies
install:
  - pip install -q six==1.11.0
  - pip install -q requests==$REQUESTS_VERSION
  - pip install -q requests-futures==0.9.5
  - pip install -q coverage
  - pip install -q coveralls

# command to run tests
script:
  - coverage run --source piprot -m unittest discover

# report coverage to coveralls.io
after_success: coveralls
